# Site settings
title: The moon of March
description: "We’ll present you beautiful memories in Seoul,Korea"
url: "https://moonofmarch.com"
author:
  name: "Irene Kim"
  email: "inhyeya317@gmail.com"
  url: "https://moonofmarch.com"

# Build settings
baseurl: /
markdown: kramdown
permalink: /:title
paginate: 8

# Default values
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed


# Custom variables
version: "1.1.0"

# Options
custom_header: false
custom_nav_footer: false
reverse: false

# 블로그 disqus shortname
disqus:
  shortname: moonofmarch-com
